spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/BookRental?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username : root
    password : Dydgus9670!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    root : debug



#  naver:
#    clientId: 'bNVcbO0zc53YrcKHePh_'
#    clientSecret: 'whYt0FcPv_'
#    clientAuthenticationMethod: post
#    authorizationGrantType: authorization_code
#    redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#    scope:
#      - email
#      - name
#    clientName: Naver
#  provider:
#    naver:
#      authorization-uri: https://nid.naver.com/oauth2.0/authorize
#      token-uri: https://nid.naver.com/oauth2.0/token
#      user-info-uri: https://openapi.naver.com/v1/nid/me
#      user-name-attribute: response