spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/BookRental?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username : root
    password : Dydgus9670!

  jpa:
    hibernate:
      ddl-auto: create
    propertise:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace